// Mocks generated by Mockito 5.4.6 from annotations
// in restaurant/test/restaurant_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant/models/restaurant-detail-model.dart' as _i2;
import 'package:restaurant/models/restaurant-list-model.dart' as _i5;
import 'package:restaurant/proxys/restaurant-proxy.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRestaurantDetailModel_0 extends _i1.SmartFake
    implements _i2.RestaurantDetailModel {
  _FakeRestaurantDetailModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RestaurantProxy].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantProxy extends _i1.Mock implements _i3.RestaurantProxy {
  MockRestaurantProxy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.RestaurantListModel>> getRestaurantList([
    _i6.BuildContext? context,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurantList, [context]),
            returnValue: _i4.Future<List<_i5.RestaurantListModel>>.value(
              <_i5.RestaurantListModel>[],
            ),
          )
          as _i4.Future<List<_i5.RestaurantListModel>>);

  @override
  _i4.Future<_i2.RestaurantDetailModel> getRestaurantDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurantDetail, [id]),
            returnValue: _i4.Future<_i2.RestaurantDetailModel>.value(
              _FakeRestaurantDetailModel_0(
                this,
                Invocation.method(#getRestaurantDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.RestaurantDetailModel>);

  @override
  _i4.Future<List<_i5.RestaurantListModel>> searchRestaurant(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchRestaurant, [query]),
            returnValue: _i4.Future<List<_i5.RestaurantListModel>>.value(
              <_i5.RestaurantListModel>[],
            ),
          )
          as _i4.Future<List<_i5.RestaurantListModel>>);

  @override
  _i4.Future<List<_i2.CustomerReview>> sendReview(
    _i6.BuildContext? context,
    String? id,
    String? name,
    String? review,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendReview, [context, id, name, review]),
            returnValue: _i4.Future<List<_i2.CustomerReview>>.value(
              <_i2.CustomerReview>[],
            ),
          )
          as _i4.Future<List<_i2.CustomerReview>>);
}
