name: restaurant
description: "Dicoding Submission App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  provider: ^6.1.5+1
  google_fonts: ^8.0.2
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.4
  flutter_local_notifications: ^21.0.0
  sqflite_dev: ^1.0.8
  flutter_timezone: ^5.0.1
  timezone: ^0.11.0
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true